// src/lib/views/Dashboard.svelte
<script>
  import { habits, completions, showCreateHabit, searchQuery, selectedCategory, categories, filteredHabits } from '../stores.js';
  import Heatmap from '../components/Heatmap.svelte';
  import HabitCard from '../components/HabitCard.svelte';
  import { getToday } from '../utils.js';

  export let refreshData;

  let today = getToday();
  let completedToday = new Set();

  $: {
    const set = new Set();
    $completions.filter(c => c.date === today).forEach(c => set.add(c.habit_id));
    completedToday = set;
  }

  function openCreateHabit() {
    showCreateHabit.set(true);
  }
</script>

<div class="dashboard">
  <div class="dashboard-header">
    <div>
      <h1 class="page-title">Dashboard</h1>
      <p class="page-subtitle">
        {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
      </p>
    </div>
    <button class="btn-primary" on:click={openCreateHabit}>
      <span>+</span> New Habit
    </button>
  </div>

  <!-- Overview Heatmap -->
  <div class="overview-section">
    <h2 class="section-title">Your Year at a Glance</h2>
    <Heatmap 
      completions={$completions}
      habits={$habits.filter(h => !h.archived)}
      type="overview"
    />
  </div>

  <!-- Today's Habits -->
  <div class="today-section">
    <h2 class="section-title">Today's Habits</h2>
    
    <!-- Filters -->
    <div class="filters">
      <input 
        type="text" 
        class="search-input"
        placeholder="Search habits..."
        bind:value={$searchQuery}
      />
      <select class="category-select" bind:value={$selectedCategory}>
        {#each $categories as cat}
          <option value={cat}>{cat}</option>
        {/each}
      </select>
    </div>

    {#if $filteredHabits.length === 0}
      <div class="empty-state">
        <div class="empty-icon">🌱</div>
        <h3>No habits yet</h3>
        <p>Start building better habits by creating your first one!</p>
        <button class="btn-primary" on:click={openCreateHabit}>
          Create Your First Habit
        </button>
      </div>
    {:else}
      <div class="habits-grid">
        {#each $filteredHabits as habit (habit.id)}
          <HabitCard 
            {habit}
            isCompleted={completedToday.has(habit.id)}
            {refreshData}
          />
        {/each}
      </div>
    {/if}
  </div>
</div>

<style>
  .dashboard {
    max-width: 1200px;
    margin: 0 auto;
  }

  .dashboard-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 2rem;
  }

  .page-title {
    font-size: 1.75rem;
    font-weight: 700;
    color: var(--text);
  }

  .page-subtitle {
    color: var(--text-secondary);
    margin-top: 0.25rem;
  }

  .btn-primary {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.625rem 1.25rem;
    background: var(--primary);
    color: white;
    border-radius: 0.5rem;
    font-weight: 600;
    font-size: 0.875rem;
    transition: all 0.15s;
  }

  .btn-primary:hover {
    background: var(--primary-dark);
    transform: translateY(-1px);
    box-shadow: var(--shadow-md);
  }

  .overview-section, .today-section {
    margin-bottom: 2.5rem;
  }

  .section-title {
    font-size: 1.125rem;
    font-weight: 600;
    margin-bottom: 1rem;
    color: var(--text);
  }

  .filters {
    display: flex;
    gap: 0.75rem;
    margin-bottom: 1.25rem;
  }

  .search-input {
    flex: 1;
    max-width: 300px;
    padding: 0.5rem 0.75rem;
    border: 1px solid var(--border);
    border-radius: 0.375rem;
    background: var(--bg);
    color: var(--text);
    font-size: 0.875rem;
  }

  .search-input:focus {
    outline: none;
    border-color: var(--primary);
    box-shadow: 0 0 0 2px rgba(16, 185, 129, 0.1);
  }

  .category-select {
    padding: 0.5rem 0.75rem;
    border: 1px solid var(--border);
    border-radius: 0.375rem;
    background: var(--bg);
    color: var(--text);
    font-size: 0.875rem;
  }

  .habits-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1rem;
  }

  .empty-state {
    text-align: center;
    padding: 3rem 2rem;
    background: var(--bg-secondary);
    border-radius: 1rem;
    border: 2px dashed var(--border);
  }

  .empty-icon {
    font-size: 3rem;
    margin-bottom: 1rem;
  }

  .empty-state h3 {
    font-size: 1.25rem;
    margin-bottom: 0.5rem;
  }

  .empty-state p {
    color: var(--text-secondary);
    margin-bottom: 1.5rem;
  }
</style>

// src/components/Habits/Dashboard.jsx
import React, { useMemo } from 'react';
import { View, Text, Button, Icon, Badge, Divider } from 'reshaped';
import { Plus, Zap, Search, LayoutGrid, List, Filter } from 'lucide-react';
import { useStore } from '../../lib/store';
import { getToday, getLast365Days, toStr } from '../../lib/utils';
import { DAILY_QUOTES } from '../../lib/constants';
import YearHeatmap from '../Heatmap/YearHeatmap';
import HabitCard from './HabitCard';

export default function Dashboard({ refreshData }) {
  const {
    habits, completions, showCreateModal, setShowCreateModal,
    searchQuery, setSearchQuery, selectedCategory, setSelectedCategory,
    setView, setQuickCheckinMode, addToast, addXp
  } = useStore();

  const activeHabits = habits.filter(h => !h.archived);
  const today = getToday();
  const categories = ['All', ...new Set(activeHabits.map(h => h.category))];

  const todayCompletions = useMemo(() => {
    return new Set(completions.filter(c => c.date === today).map(c => c.habit_id));
  }, [completions, today]);

  const filtered = useMemo(() => {
    return activeHabits.filter(h => {
      const matchSearch = !searchQuery || h.name.toLowerCase().includes(searchQuery.toLowerCase());
      const matchCat = selectedCategory === 'All' || h.category === selectedCategory;
      return matchSearch && matchCat;
    });
  }, [activeHabits, searchQuery, selectedCategory]);

  const quote = DAILY_QUOTES[new Date().getDate() % DAILY_QUOTES.length];
  const completionPct = activeHabits.length > 0
    ? Math.round((todayCompletions.size / activeHabits.length) * 100) : 0;

  return (
    <div>
      {/* Header */}
      <View direction="row" align="center" gap={4} paddingBottom={6} style={{ justifyContent: 'space-between', flexWrap: 'wrap' }}>
        <View>
          <Text variant="title-1" weight="bold">
            Good {new Date().getHours() < 12 ? 'morning' : new Date().getHours() < 17 ? 'afternoon' : 'evening'} 👋
          </Text>
          <Text variant="body-2" color="neutral-faded">
            {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
          </Text>
        </View>
        <View direction="row" gap={2}>
          <Button
            variant="faded"
            color="neutral"
            startIcon={<Icon svg={<Zap size={16} />} />}
            onClick={() => setQuickCheckinMode(true)}
          >
            Quick Check-in
          </Button>
          <Button
            color="primary"
            startIcon={<Icon svg={<Plus size={16} />} />}
            onClick={() => setShowCreateModal(true)}
          >
            New Habit
          </Button>
        </View>
      </View>

      {/* Daily Quote */}
      <View padding={4} marginBottom={6} style={{
        background: 'linear-gradient(135deg, rgba(34,197,94,0.06), rgba(59,130,246,0.04))',
        borderRadius: 12, border: '1px solid rgba(34,197,94,0.15)'
      }}>
        <Text variant="body-3" color="neutral-faded" style={{ fontStyle: 'italic' }}>
          ✨ {quote}
        </Text>
      </View>

      {/* Today Progress Bar */}
      <View marginBottom={6} padding={4} style={{
        background: 'var(--rs-color-background-neutral-default)',
        border: '1px solid var(--rs-color-border-neutral-faded)',
        borderRadius: 12, boxShadow: '0 2px 8px rgba(0,0,0,0.04)'
      }}>
        <View direction="row" align="center" gap={3} style={{ justifyContent: 'space-between', marginBottom: 8 }}>
          <Text variant="body-2" weight="bold">Today's Progress</Text>
          <View direction="row" gap={2} align="center">
            <Badge color="primary" variant="faded" rounded size="small">
              {todayCompletions.size} / {activeHabits.length}
            </Badge>
            <Text variant="featured-2" weight="bold" color={completionPct === 100 ? 'success' : 'neutral'}>
              {completionPct}%
            </Text>
          </View>
        </View>
        <div style={{
          height: 8, borderRadius: 4, background: 'var(--rs-color-background-neutral-faded)',
          overflow: 'hidden'
        }}>
          <div style={{
            height: '100%', borderRadius: 4, transition: 'width 0.8s cubic-bezier(0.4, 0, 0.2, 1)',
            width: `${completionPct}%`,
            background: completionPct === 100
              ? 'linear-gradient(90deg, #22c55e, #16a34a)'
              : 'linear-gradient(90deg, #3b82f6, #22c55e)',
          }} />
        </div>
      </View>

      {/* Year Heatmap */}
      <View marginBottom={6}>
        <Text variant="title-3" weight="bold" marginBottom={3}>Your Year at a Glance</Text>
        <YearHeatmap completions={completions} habits={activeHabits} />
      </View>

      <Divider marginBottom={6} />

      {/* Today's Habits */}
      <View direction="row" align="center" gap={3} marginBottom={4} style={{ justifyContent: 'space-between', flexWrap: 'wrap' }}>
        <Text variant="title-3" weight="bold">Today's Habits</Text>
        <View direction="row" gap={2} align="center">
          <div style={{ position: 'relative' }}>
            <input
              type="text"
              placeholder="Search habits..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{
                padding: '6px 12px 6px 32px', borderRadius: 8,
                border: '1px solid var(--rs-color-border-neutral-faded)',
                background: 'var(--rs-color-background-neutral-default)',
                color: 'var(--rs-color-foreground-neutral-default)',
                fontSize: '0.8125rem', outline: 'none', width: 200,
              }}
            />
            <Search size={14} style={{ position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)', color: 'var(--rs-color-foreground-neutral-faded)' }} />
          </div>
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            style={{
              padding: '6px 12px', borderRadius: 8,
              border: '1px solid var(--rs-color-border-neutral-faded)',
              background: 'var(--rs-color-background-neutral-default)',
              color: 'var(--rs-color-foreground-neutral-default)',
              fontSize: '0.8125rem',
            }}
          >
            {categories.map(c => <option key={c} value={c}>{c}</option>)}
          </select>
        </View>
      </View>

      {filtered.length === 0 ? (
        <View padding={10} align="center" style={{
          background: 'var(--rs-color-background-neutral-faded)',
          borderRadius: 16, border: '2px dashed var(--rs-color-border-neutral-faded)',
          textAlign: 'center'
        }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>🌱</div>
          <Text variant="title-3" weight="bold" marginBottom={2}>
            {activeHabits.length === 0 ? 'Start your habit journey' : 'No habits match'}
          </Text>
          <Text variant="body-2" color="neutral-faded" marginBottom={4}>
            {activeHabits.length === 0
              ? 'Create your first habit to begin tracking your progress'
              : 'Try adjusting your search or filter'}
          </Text>
          {activeHabits.length === 0 && (
            <Button color="primary" size="large" onClick={() => setShowCreateModal(true)}
              startIcon={<Icon svg={<Plus size={16} />} />}>
              Create Your First Habit
            </Button>
          )}
        </View>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '1rem' }}>
          {filtered.map((habit, i) => (
            <div key={habit.id} className={`animate-slide-up stagger-${(i % 6) + 1}`}>
              <HabitCard
                habit={habit}
                isCompleted={todayCompletions.has(habit.id)}
                refreshData={refreshData}
              />
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
