// src/lib/components/HabitCard.svelte
<script>
  import { toggleCompletion } from '../db.js';
  import { getToday, getCurrentStreak } from '../utils.js';
  import { completions, currentView, selectedHabitId, showEditHabit, editingHabit } from '../stores.js';

  export let habit;
  export let isCompleted;
  export let refreshData;

  let currentStreak = 0;

  $: {
    const habitCompletions = $completions.filter(c => c.habit_id === habit.id);
    currentStreak = getCurrentStreak(habitCompletions);
  }

  async function handleToggle() {
    const today = getToday();
    await toggleCompletion(habit.id, today);
    await refreshData();
  }

  function openHabitPage() {
    selectedHabitId.set(habit.id);
    currentView.set('habit');
  }

  function openEdit(e) {
    e.stopPropagation();
    editingHabit.set(habit);
    showEditHabit.set(true);
  }
</script>

<div class="habit-card" class:completed={isCompleted} on:click={openHabitPage} on:keydown={(e) => e.key === 'Enter' && openHabitPage()} tabindex="0" role="button">
  <div class="card-header">
    <div class="habit-icon" style="background: {habit.color}20; color: {habit.color}">
      {habit.icon || '✨'}
    </div>
    <div class="habit-info">
      <h3 class="habit-name">{habit.name}</h3>
      <span class="habit-category">{habit.category}</span>
    </div>
    <button class="edit-btn" on:click={openEdit} title="Edit habit">
      ✏️
    </button>
  </div>

  <div class="card-body">
    <div class="streak-info">
      <span class="streak-icon">🔥</span>
      <span class="streak-count">{currentStreak}</span>
      <span class="streak-label">day streak</span>
    </div>
  </div>

  <div class="card-footer">
    <button 
      class="check-btn"
      class:checked={isCompleted}
      on:click={(e) => { e.stopPropagation(); handleToggle(); }}
      title={isCompleted ? 'Mark as incomplete' : 'Mark as complete'}
    >
      {#if isCompleted}
        ✓ Done
      {:else}
        ○ Mark Done
      {/if}
    </button>
  </div>
</div>

<style>
  .habit-card {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 0.75rem;
    padding: 1.25rem;
    cursor: pointer;
    transition: all 0.2s;
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .habit-card:hover {
    border-color: var(--primary);
    box-shadow: var(--shadow-md);
    transform: translateY(-2px);
  }

  .habit-card.completed {
    border-color: var(--primary);
    background: linear-gradient(135deg, var(--bg), rgba(16, 185, 129, 0.05));
  }

  .card-header {
    display: flex;
    align-items: flex-start;
    gap: 0.75rem;
  }

  .habit-icon {
    width: 2.5rem;
    height: 2.5rem;
    border-radius: 0.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.25rem;
    flex-shrink: 0;
  }

  .habit-info {
    flex: 1;
    min-width: 0;
  }

  .habit-name {
    font-size: 1rem;
    font-weight: 600;
    color: var(--text);
    margin-bottom: 0.125rem;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .habit-category {
    font-size: 0.75rem;
    color: var(--text-secondary);
    background: var(--bg-tertiary);
    padding: 0.125rem 0.5rem;
    border-radius: 9999px;
    display: inline-block;
  }

  .edit-btn {
    padding: 0.25rem;
    border-radius: 0.25rem;
    opacity: 0;
    transition: opacity 0.15s;
    font-size: 0.875rem;
  }

  .habit-card:hover .edit-btn {
    opacity: 1;
  }

  .edit-btn:hover {
    background: var(--bg-tertiary);
  }

  .card-body {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .streak-info {
    display: flex;
    align-items: center;
    gap: 0.375rem;
    font-size: 0.875rem;
  }

  .streak-icon {
    font-size: 1rem;
  }

  .streak-count {
    font-weight: 700;
    color: var(--text);
    font-size: 1.125rem;
  }

  .streak-label {
    color: var(--text-secondary);
    font-size: 0.8125rem;
  }

  .card-footer {
    margin-top: auto;
  }

  .check-btn {
    width: 100%;
    padding: 0.5rem;
    border: 2px solid var(--border);
    border-radius: 0.5rem;
    font-weight: 600;
    font-size: 0.875rem;
    color: var(--text-secondary);
    transition: all 0.15s;
  }

  .check-btn:hover {
    border-color: var(--primary);
    color: var(--primary);
    background: rgba(16, 185, 129, 0.05);
  }

  .check-btn.checked {
    background: var(--primary);
    border-color: var(--primary);
    color: white;
  }
</style>

// src/components/Habits/HabitCard.jsx
import React, { useMemo } from 'react';
import { View, Text, Icon, Badge, Tooltip } from 'reshaped';
import { Flame, Trophy, Check, Circle, MoreHorizontal } from 'lucide-react';
import { useStore } from '../../lib/store';
import { toggleCompletion } from '../../lib/db';
import { getToday, getCurrentStreak, getLongestStreak } from '../../lib/utils';
import { CATEGORIES } from '../../lib/constants';

export default function HabitCard({ habit, isCompleted, refreshData }) {
  const { completions, setView, addToast, addXp, unlockAchievement } = useStore();

  const habitCompletions = useMemo(
    () => completions.filter(c => c.habit_id === habit.id),
    [completions, habit.id]
  );
  const streak = getCurrentStreak(habitCompletions);
  const longest = getLongestStreak(habitCompletions);
  const cat = CATEGORIES.find(c => c.name === habit.category);

  async function handleToggle(e) {
    e.stopPropagation();
    const today = getToday();
    const wasAdded = await toggleCompletion(habit.id, today);
    await refreshData();

    if (wasAdded) {
      addXp(10);
      addToast({ type: 'success', message: `✅ ${habit.name} completed! +10 XP` });

      // Check time-based achievements
      const hour = new Date().getHours();
      if (hour < 7) unlockAchievement('early_bird');
      if (hour >= 22) unlockAchievement('night_owl');

      // Check streak milestones
      if (streak + 1 >= 3) unlockAchievement('streak_3');
      if (streak + 1 >= 7) unlockAchievement('streak_7');
      if (streak + 1 >= 30) unlockAchievement('streak_30');

      // Confetti for milestones
      const newStreak = streak + 1;
      if (newStreak % 7 === 0 || newStreak % 30 === 0) {
        try {
          const confetti = (await import('canvas-confetti')).default;
          confetti({ particleCount: 100, spread: 70, origin: { y: 0.6 } });
        } catch {}
      }
    }
  }

  function openPage() {
    setView('habit', habit.id);
  }

  return (
    <div
      className={`habit-card ${isCompleted ? 'completed' : ''}`}
      style={{ '--accent-color': habit.color }}
      onClick={openPage}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => e.key === 'Enter' && openPage()}
    >
      {/* Header */}
      <View direction="row" align="start" gap={3} marginBottom={3}>
        <div style={{
          width: 44, height: 44, borderRadius: 12,
          background: `${habit.color}18`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: '1.5rem', flexShrink: 0,
          boxShadow: `0 2px 8px ${habit.color}20`
        }}>
          {habit.icon || '✨'}
        </div>
        <View style={{ flex: 1, minWidth: 0 }}>
          <Text variant="body-1" weight="bold" style={{
            overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap'
          }}>
            {habit.name}
          </Text>
          <View direction="row" gap={1} align="center" marginTop={1}>
            <Badge size="small" variant="faded" color="neutral" rounded>
              {habit.category}
            </Badge>
            {habit.frequency !== 'daily' && (
              <Badge size="small" variant="faded" color="neutral" rounded>
                {habit.frequency}
              </Badge>
            )}
          </View>
        </View>
      </View>

      {/* Stats row */}
      <View direction="row" gap={4} marginBottom={3}>
        <View direction="row" gap={1} align="center">
          <Flame size={14} color="#f97316" />
          <Text variant="caption-1" weight="bold">{streak}</Text>
          <Text variant="caption-2" color="neutral-faded">streak</Text>
        </View>
        <View direction="row" gap={1} align="center">
          <Trophy size={14} color="#eab308" />
          <Text variant="caption-1" weight="bold">{longest}</Text>
          <Text variant="caption-2" color="neutral-faded">best</Text>
        </View>
      </View>

      {/* Mini heatmap (last 7 days) */}
      <View direction="row" gap={1} marginBottom={3}>
        {Array.from({ length: 7 }).map((_, i) => {
          const d = new Date();
          d.setDate(d.getDate() - (6 - i));
          const ds = d.toISOString().split('T')[0];
          const has = habitCompletions.some(c => c.date === ds);
          return (
            <div key={i} style={{
              width: '100%', height: 6, borderRadius: 3,
              background: has ? habit.color : 'var(--rs-color-background-neutral-faded)',
              opacity: has ? 1 : 0.5,
              transition: 'all 0.3s'
            }} />
          );
        })}
      </View>

      {/* Action button */}
      <button
        onClick={handleToggle}
        style={{
          width: '100%', padding: '0.5rem', borderRadius: 8,
          border: `2px solid ${isCompleted ? habit.color : 'var(--rs-color-border-neutral-faded)'}`,
          background: isCompleted ? `${habit.color}10` : 'transparent',
          color: isCompleted ? habit.color : 'var(--rs-color-foreground-neutral-faded)',
          fontWeight: 600, fontSize: '0.8125rem', cursor: 'pointer',
          display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.375rem',
          transition: 'all 0.2s',
        }}
        onMouseEnter={(e) => {
          if (!isCompleted) {
            e.currentTarget.style.borderColor = habit.color;
            e.currentTarget.style.color = habit.color;
          }
        }}
        onMouseLeave={(e) => {
          if (!isCompleted) {
            e.currentTarget.style.borderColor = 'var(--rs-color-border-neutral-faded)';
            e.currentTarget.style.color = 'var(--rs-color-foreground-neutral-faded)';
          }
        }}
      >
        {isCompleted ? (
          <><Check size={16} /> Done!</>
        ) : (
          <><Circle size={16} /> Mark Done</>
        )}
      </button>
    </div>
  );
}
