// src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { 
    currentView, theme, isAuthenticated, passwordEnabled,
    tutorialCompleted, habits, completions, journalEntries, settings
  } from './lib/stores.js';
  import { getHabits, getCompletions, getJournalEntries, getAllSettings, getSetting, saveSetting } from './lib/db.js';
  import Sidebar from './lib/components/Sidebar.svelte';
  import Dashboard from './lib/views/Dashboard.svelte';
  import HabitPage from './lib/views/HabitPage.svelte';
  import Journal from './lib/views/Journal.svelte';
  import SettingsView from './lib/views/SettingsView.svelte';
  import Tutorial from './lib/views/Tutorial.svelte';
  import PasswordGate from './lib/components/PasswordGate.svelte';
  import CreateHabitModal from './lib/components/CreateHabitModal.svelte';
  import { showCreateHabit } from './lib/stores.js';

  let isLoading = true;

  onMount(async () => {
    try {
      // Load theme
      const savedTheme = await getSetting('theme');
      if (savedTheme) {
        theme.set(savedTheme);
        document.documentElement.setAttribute('data-theme', savedTheme);
      }

      // Check password protection
      const pwdHash = await getSetting('password_hash');
      if (pwdHash) {
        passwordEnabled.set(true);
        isAuthenticated.set(false);
      } else {
        isAuthenticated.set(true);
      }

      // Check tutorial
      const tutorialDone = await getSetting('tutorial_completed');
      if (!tutorialDone) {
        tutorialCompleted.set(false);
        currentView.set('tutorial');
      } else {
        tutorialCompleted.set(true);
      }

      // Load all data
      await refreshData();
    } catch (e) {
      console.error('Init error:', e);
    } finally {
      isLoading = false;
    }
  });

  async function refreshData() {
    const [h, c, j, s] = await Promise.all([
      getHabits(),
      getCompletions(),
      getJournalEntries(),
      getAllSettings()
    ]);
    habits.set(h);
    completions.set(c);
    journalEntries.set(j);
    settings.set(s);
  }

  // Make refreshData available to child components
  import { setContext } from 'svelte';
  setContext('refreshData', refreshData);

  theme.subscribe(value => {
    document.documentElement.setAttribute('data-theme', value);
  });
</script>

{#if isLoading}
  <div class="loading">
    <div class="loading-spinner"></div>
    <p>Loading Habitt...</p>
  </div>
{:else if !isAuthenticated}
  <PasswordGate />
{:else if $currentView === 'tutorial'}
  <Tutorial />
{:else}
  <div class="app-layout">
    <Sidebar />
    <main class="main-content">
      {#if $currentView === 'dashboard'}
        <Dashboard {refreshData} />
      {:else if $currentView === 'habit'}
        <HabitPage {refreshData} />
      {:else if $currentView === 'journal'}
        <Journal {refreshData} />
      {:else if $currentView === 'settings'}
        <SettingsView {refreshData} />
      {/if}
    </main>
  </div>
{/if}

{#if $showCreateHabit}
  <CreateHabitModal {refreshData} />
{/if}

<style>
  .loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 100vw;
    height: 100vh;
    gap: 1rem;
    color: var(--text-secondary);
  }

  .loading-spinner {
    width: 40px;
    height: 40px;
    border: 3px solid var(--border);
    border-top-color: var(--primary);
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .app-layout {
    display: flex;
    width: 100vw;
    height: 100vh;
    overflow: hidden;
  }

  .main-content {
    flex: 1;
    overflow-y: auto;
    padding: 2rem;
    background: var(--bg);
  }
</style>

// src/App.jsx
import React, { useEffect, useCallback } from 'react';
import { Reshaped, Theme } from 'reshaped';
import 'reshaped/themes/slate/theme.css';
import { useStore } from './lib/store';
import { getHabits, getCompletions, getJournalEntries, getAllSettings, getSetting } from './lib/db';
import Sidebar from './components/Layout/Sidebar';
import Dashboard from './components/Habits/Dashboard';
import HabitDetailPage from './components/Habits/HabitDetailPage';
import JournalPage from './components/Journal/JournalPage';
import StatsDashboard from './components/Stats/StatsDashboard';
import SettingsPage from './components/Settings/SettingsPage';
import Tutorial from './components/Tutorial/Tutorial';
import PasswordGate from './components/Shared/PasswordGate';
import CreateHabitModal from './components/Habits/CreateHabitModal';
import CommandPalette from './components/Shared/CommandPalette';
import ToastContainer from './components/Shared/ToastContainer';
import QuickCheckin from './components/Habits/QuickCheckin';

export default function App() {
  const {
    currentView, colorMode, setColorMode, isAuthenticated, passwordEnabled,
    setPasswordEnabled, setAuthenticated, tutorialDone, setTutorialDone,
    setHabits, setCompletions, setJournalEntries, showCreateModal,
    showCommandPalette, setShowCommandPalette, quickCheckinMode,
    setQuickCheckinMode, toasts
  } = useStore();

  const [loading, setLoading] = React.useState(true);

  const refreshData = useCallback(async () => {
    try {
      const [h, c, j] = await Promise.all([getHabits(), getCompletions(), getJournalEntries()]);
      setHabits(h); setCompletions(c); setJournalEntries(j);
    } catch (e) { console.error('Refresh error:', e); }
  }, [setHabits, setCompletions, setJournalEntries]);

  useEffect(() => {
    (async () => {
      try {
        const theme = await getSetting('theme');
        if (theme) { setColorMode(theme); }
        const pwd = await getSetting('password_hash');
        if (pwd) { setPasswordEnabled(true); } else { setAuthenticated(true); }
        const tut = await getSetting('tutorial_completed');
        if (tut) setTutorialDone(true);
        await refreshData();
      } catch (e) { console.error('Init error:', e); setAuthenticated(true); }
      finally { setLoading(false); }
    })();
  }, []);

  // Keyboard shortcuts
  useEffect(() => {
    const handler = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        setShowCommandPalette(true);
      }
      if ((e.metaKey || e.ctrlKey) && e.key === 'n') {
        e.preventDefault();
        useStore.setState({ showCreateModal: true });
      }
      if (e.key === 'Escape') {
        setShowCommandPalette(false);
        useStore.setState({ showCreateModal: false, showTemplateLibrary: false });
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, []);

  if (loading) {
    return (
      <Reshaped theme="slate" colorMode={colorMode}>
        <div style={{ display:'flex', alignItems:'center', justifyContent:'center', height:'100vh', flexDirection:'column', gap:'1rem' }}>
          <div style={{ fontSize:'3rem' }}>🌱</div>
          <div style={{ fontSize:'1.25rem', fontWeight:700, color:'var(--rs-color-foreground-neutral-default)' }}>Habitt.</div>
          <div style={{ color:'var(--rs-color-foreground-neutral-faded)', fontSize:'0.875rem' }}>Loading your habits...</div>
        </div>
      </Reshaped>
    );
  }

  if (!isAuthenticated) {
    return (
      <Reshaped theme="slate" colorMode={colorMode}>
        <PasswordGate />
      </Reshaped>
    );
  }

  if (!tutorialDone && currentView !== 'settings') {
    return (
      <Reshaped theme="slate" colorMode={colorMode}>
        <Tutorial />
      </Reshaped>
    );
  }

  const renderView = () => {
    switch (currentView) {
      case 'dashboard': return <Dashboard refreshData={refreshData} />;
      case 'habit': return <HabitDetailPage refreshData={refreshData} />;
      case 'journal': return <JournalPage refreshData={refreshData} />;
      case 'stats': return <StatsDashboard />;
      case 'settings': return <SettingsPage refreshData={refreshData} />;
      default: return <Dashboard refreshData={refreshData} />;
    }
  };

  return (
    <Reshaped theme="slate" colorMode={colorMode}>
      <div className="app-shell">
        <Sidebar />
        <main className="app-main">
          {quickCheckinMode ? (
            <QuickCheckin refreshData={refreshData} />
          ) : (
            <div className="app-main-inner animate-fade-in" key={currentView}>
              {renderView()}
            </div>
          )}
        </main>
      </div>
      {showCreateModal && <CreateHabitModal refreshData={refreshData} />}
      {showCommandPalette && <CommandPalette />}
      <ToastContainer />
    </Reshaped>
  );
}
