// src/components/Habits/CreateHabitModal.jsx
import React, { useState, useEffect } from 'react';
import { View, Text, Button, Icon, Modal, TextField, TextArea, Select, Switch, Slider } from 'reshaped';
import { Plus, Sparkles, BookOpen } from 'lucide-react';
import { useStore } from '../../lib/store';
import { createHabit, updateHabit } from '../../lib/db';
import { COLORS, CATEGORIES, HABIT_TEMPLATES, FREQUENCY_OPTIONS } from '../../lib/constants';

export default function CreateHabitModal({ refreshData }) {
  const { showCreateModal, setShowCreateModal, editingHabit, setEditingHabit,
    setShowTemplateLibrary, addToast, addXp, unlockAchievement, habits } = useStore();

  const isEdit = !!editingHabit;
  const [form, setForm] = useState({
    name: '', description: '', icon: '✨', color: '#22c55e',
    category: 'General', frequency: 'daily', target_count: 1,
    reminder_enabled: false, reminder_time: '09:00', custom_days: '',
    difficulty: 'medium', notes_template: '',
  });

  useEffect(() => {
    if (editingHabit) setForm({ ...editingHabit });
    else setForm({
      name: '', description: '', icon: '✨', color: '#22c55e',
      category: 'General', frequency: 'daily', target_count: 1,
      reminder_enabled: false, reminder_time: '09:00', custom_days: '',
      difficulty: 'medium', notes_template: '',
    });
  }, [editingHabit]);

  function update(field, value) { setForm(f => ({ ...f, [field]: value })); }

  async function handleSubmit(e) {
    e?.preventDefault?.();
    if (!form.name.trim()) return;
    if (isEdit) {
      await updateHabit(form.id, form);
      addToast({ type: 'success', message: '✅ Habit updated!' });
    } else {
      await createHabit(form);
      addXp(20);
      addToast({ type: 'success', message: '🎉 Habit created! +20 XP' });
      if (habits.length === 0) unlockAchievement('first_habit');
      if (habits.length === 4) unlockAchievement('five_habits');
      if (habits.length === 9) unlockAchievement('ten_habits');
    }
    await refreshData();
    close();
  }

  function close() {
    setShowCreateModal(false);
    setEditingHabit(null);
  }

  function useTemplate(t) {
    setForm(f => ({ ...f, name: t.name, icon: t.icon, category: t.category, description: t.description, target_count: t.target || 1 }));
  }

  const EMOJI_SET = ['💪','🏃','🧘','📚','💧','🥗','😴','🎯','✍️','🎨','🎵','💻','🌱','☀️','🌙','❤️','🧠','🎓','💼','🏠','🚶','🚴','🏊','⚡','🔥','⭐','✨','🌟','🎉','🏆','📖','🧹','💊','☕','📵','🙏','🌲','📸','🎧','🚿'];

  return (
    <div style={{
      position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)',
      backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center',
      justifyContent: 'center', zIndex: 1000, padding: '1rem'
    }} onClick={(e) => e.target === e.currentTarget && close()}>
      <div className="animate-scale-in" style={{
        background: 'var(--rs-color-background-neutral-default)',
        borderRadius: 16, width: '100%', maxWidth: 560, maxHeight: '90vh',
        overflow: 'auto', boxShadow: '0 20px 60px rgba(0,0,0,0.15)'
      }}>
        {/* Header */}
        <View direction="row" align="center" padding={5} style={{
          justifyContent: 'space-between', borderBottom: '1px solid var(--rs-color-border-neutral-faded)'
        }}>
          <Text variant="title-3" weight="bold">{isEdit ? 'Edit Habit' : 'Create New Habit'}</Text>
          <button onClick={close} style={{
            width: 32, height: 32, borderRadius: 8, border: 'none', cursor: 'pointer',
            background: 'var(--rs-color-background-neutral-faded)', fontSize: '1rem',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>✕</button>
        </View>

        <form onSubmit={handleSubmit}>
          <View padding={5} gap={4}>
            {/* Templates quick-add */}
            {!isEdit && (
              <View>
                <Text variant="caption-1" weight="bold" color="neutral-faded" marginBottom={2}>Quick Templates</Text>
                <div style={{ display: 'flex', gap: 8, overflowX: 'auto', paddingBottom: 4 }}>
                  {HABIT_TEMPLATES.slice(0, 8).map((t, i) => (
                    <button key={i} type="button" onClick={() => useTemplate(t)} style={{
                      padding: '6px 12px', borderRadius: 8, border: '1px solid var(--rs-color-border-neutral-faded)',
                      background: 'var(--rs-color-background-neutral-faded)', cursor: 'pointer',
                      whiteSpace: 'nowrap', fontSize: '0.75rem', fontWeight: 500,
                      display: 'flex', alignItems: 'center', gap: 4,
                    }}>
                      {t.icon} {t.name}
                    </button>
                  ))}
                </div>
              </View>
            )}

            {/* Icon & Color */}
            <View>
              <Text variant="caption-1" weight="bold" color="neutral-faded" marginBottom={2}>Icon & Color</Text>
              <View direction="row" gap={3} align="center">
                <div style={{
                  width: 56, height: 56, borderRadius: 14,
                  background: `${form.color}18`, display: 'flex',
                  alignItems: 'center', justifyContent: 'center', fontSize: '2rem',
                  border: `2px solid ${form.color}40`,
                }}>
                  {form.icon}
                </div>
                <View style={{ flex: 1 }}>
                  <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap', marginBottom: 8 }}>
                    {EMOJI_SET.slice(0, 16).map(e => (
                      <button key={e} type="button" onClick={() => update('icon', e)} style={{
                        width: 28, height: 28, borderRadius: 6, border: form.icon === e ? `2px solid ${form.color}` : '2px solid transparent',
                        background: form.icon === e ? `${form.color}15` : 'transparent',
                        cursor: 'pointer', fontSize: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'center',
                      }}>{e}</button>
                    ))}
                  </div>
                  <div style={{ display: 'flex', gap: 6 }}>
                    {COLORS.map(c => (
                      <button key={c} type="button" onClick={() => update('color', c)} style={{
                        width: 24, height: 24, borderRadius: '50%', background: c,
                        border: form.color === c ? '3px solid var(--rs-color-foreground-neutral-default)' : '2px solid transparent',
                        cursor: 'pointer', boxShadow: form.color === c ? `0 0 0 2px var(--rs-color-background-neutral-default), 0 0 0 4px ${c}` : 'none',
                        transition: 'all 0.15s',
                      }} />
                    ))}
                  </div>
                </View>
              </View>
            </View>

            {/* Name */}
            <TextField
              label="Habit Name"
              placeholder="e.g., Read for 30 minutes"
              value={form.name}
              onChange={({ value }) => update('name', value)}
              required
            />

            {/* Description */}
            <TextArea
              label="Description"
              placeholder="Why is this habit important to you?"
              value={form.description}
              onChange={({ value }) => update('description', value)}
              rows={2}
            />

            {/* Category & Frequency */}
            <View direction="row" gap={3}>
              <div style={{ flex: 1 }}>
                <Select
                  label="Category"
                  value={form.category}
                  onChange={({ value }) => update('category', value)}
                >
                  {CATEGORIES.map(c => (
                    <option key={c.name} value={c.name}>{c.icon} {c.name}</option>
                  ))}
                </Select>
              </div>
              <div style={{ flex: 1 }}>
                <Select
                  label="Frequency"
                  value={form.frequency}
                  onChange={({ value }) => update('frequency', value)}
                >
                  {FREQUENCY_OPTIONS.map(f => (
                    <option key={f.value} value={f.value}>{f.label}</option>
                  ))}
                </Select>
              </div>
            </View>

            {/* Difficulty */}
            <View>
              <Text variant="caption-1" weight="bold" color="neutral-faded" marginBottom={2}>Difficulty</Text>
              <View direction="row" gap={2}>
                {['easy', 'medium', 'hard'].map(d => (
                  <button key={d} type="button" onClick={() => update('difficulty', d)} style={{
                    flex: 1, padding: '8px 12px', borderRadius: 8, cursor: 'pointer',
                    border: `2px solid ${form.difficulty === d ? (d === 'easy' ? '#22c55e' : d === 'medium' ? '#f59e0b' : '#ef4444') : 'var(--rs-color-border-neutral-faded)'}`,
                    background: form.difficulty === d ? (d === 'easy' ? 'rgba(34,197,94,0.08)' : d === 'medium' ? 'rgba(245,158,11,0.08)' : 'rgba(239,68,68,0.08)') : 'transparent',
                    fontWeight: 600, fontSize: '0.8125rem', textTransform: 'capitalize',
                    color: form.difficulty === d ? (d === 'easy' ? '#22c55e' : d === 'medium' ? '#f59e0b' : '#ef4444') : 'var(--rs-color-foreground-neutral-default)',
                  }}>
                    {d === 'easy' ? '😊' : d === 'medium' ? '💪' : '🔥'} {d}
                  </button>
                ))}
              </View>
            </View>

            {/* Target count */}
            <View direction="row" gap={3} align="center">
              <Text variant="body-3">Daily target:</Text>
              <View direction="row" gap={1} align="center">
                <button type="button" onClick={() => update('target_count', Math.max(1, form.target_count - 1))}
                  style={{ width: 28, height: 28, borderRadius: 6, border: '1px solid var(--rs-color-border-neutral-faded)', background: 'var(--rs-color-background-neutral-faded)', cursor: 'pointer', fontWeight: 700 }}>−</button>
                <Text variant="featured-2" weight="bold" style={{ minWidth: 32, textAlign: 'center' }}>{form.target_count}</Text>
                <button type="button" onClick={() => update('target_count', Math.min(99, form.target_count + 1))}
                  style={{ width: 28, height: 28, borderRadius: 6, border: '1px solid var(--rs-color-border-neutral-faded)', background: 'var(--rs-color-background-neutral-faded)', cursor: 'pointer', fontWeight: 700 }}>+</button>
              </View>
            </View>
          </View>

          {/* Footer */}
          <View direction="row" gap={2} padding={5} style={{
            justifyContent: 'flex-end', borderTop: '1px solid var(--rs-color-border-neutral-faded)',
          }}>
            <Button variant="faded" color="neutral" onClick={close}>Cancel</Button>
            <Button type="submit" color="primary" disabled={!form.name.trim()}
              startIcon={<Icon svg={<Plus size={16} />} />}>
              {isEdit ? 'Save Changes' : 'Create Habit'}
            </Button>
          </View>
        </form>
      </div>
    </div>
  );
}

// src/lib/components/CreateHabitModal.svelte
<script>
  import { createHabit, updateHabit } from '../db.js';
  import { showCreateHabit, showEditHabit, editingHabit } from '../stores.js';
  import { HABIT_ICONS, HABIT_COLORS, CATEGORIES } from '../utils.js';

  export let refreshData;

  let mode = 'create'; // 'create' or 'edit'
  let form = {
    name: '',
    description: '',
    icon: '✨',
    color: '#10b981',
    category: 'General',
    frequency: 'daily',
    target_count: 1,
    reminder_enabled: false,
    reminder_time: '09:00'
  };

  let showIconPicker = false;
  let showColorPicker = false;

  // Check if editing
  $: if ($showEditHabit && $editingHabit) {
    mode = 'edit';
    form = { ...$editingHabit };
  } else if ($showCreateHabit) {
    mode = 'create';
    form = {
      name: '',
      description: '',
      icon: '✨',
      color: '#10b981',
      category: 'General',
      frequency: 'daily',
      target_count: 1,
      reminder_enabled: false,
      reminder_time: '09:00'
    };
  }

  async function handleSubmit() {
    if (!form.name.trim()) return;

    if (mode === 'edit') {
      await updateHabit(form.id, form);
    } else {
      await createHabit(form);
    }

    await refreshData();
    close();
  }

  function close() {
    showCreateHabit.set(false);
    showEditHabit.set(false);
    editingHabit.set(null);
    showIconPicker = false;
    showColorPicker = false;
  }

  function backdropClick(e) {
    if (e.target === e.currentTarget) close();
  }
</script>

{#if $showCreateHabit || $showEditHabit}
  <div class="modal-backdrop" on:click={backdropClick} on:keydown={(e) => e.key === 'Escape' && close()} role="dialog" aria-modal="true">
    <div class="modal">
      <div class="modal-header">
        <h2>{mode === 'edit' ? 'Edit Habit' : 'Create New Habit'}</h2>
        <button class="close-btn" on:click={close}>✕</button>
      </div>

      <form on:submit|preventDefault={handleSubmit} class="modal-body">
        <!-- Icon & Color Selection -->
        <div class="icon-color-row">
          <div class="icon-selector">
            <button 
              type="button" 
              class="icon-display" 
              style="background: {form.color}20"
              on:click={() => showIconPicker = !showIconPicker}
            >
              {form.icon}
            </button>
            {#if showIconPicker}
              <div class="icon-picker">
                {#each HABIT_ICONS as icon}
                  <button
                    type="button"
                    class="icon-option"
                    class:selected={form.icon === icon}
                    on:click={() => { form.icon = icon; showIconPicker = false; }}
                  >
                    {icon}
                  </button>
                {/each}
              </div>
            {/if}
          </div>

          <div class="color-selector">
            {#each HABIT_COLORS as color}
              <button
                type="button"
                class="color-option"
                class:selected={form.color === color}
                style="background: {color}"
                on:click={() => form.color = color}
              ></button>
            {/each}
          </div>
        </div>

        <!-- Name -->
        <div class="form-group">
          <label for="name">Habit Name *</label>
          <input 
            id="name"
            type="text" 
            bind:value={form.name}
            placeholder="e.g., Read for 30 minutes"
            required
          />
        </div>

        <!-- Description -->
        <div class="form-group">
          <label for="description">Description</label>
          <textarea 
            id="description"
            bind:value={form.description}
            placeholder="Why is this habit important to you?"
            rows="2"
          ></textarea>
        </div>

        <!-- Category -->
        <div class="form-group">
          <label for="category">Category</label>
          <select id="category" bind:value={form.category}>
            {#each CATEGORIES as cat}
              <option value={cat}>{cat}</option>
            {/each}
          </select>
        </div>

        <!-- Frequency & Target -->
        <div class="form-row">
          <div class="form-group">
            <label for="frequency">Frequency</label>
            <select id="frequency" bind:value={form.frequency}>
              <option value="daily">Daily</option>
              <option value="weekly">Weekly</option>
              <option value="monthly">Monthly</option>
            </select>
          </div>

          <div class="form-group">
            <label for="target">Target per day</label>
            <input 
              id="target"
              type="number" 
              min="1" 
              max="99"
              bind:value={form.target_count}
            />
          </div>
        </div>

        <!-- Reminder -->
        <div class="form-group reminder-group">
          <label class="checkbox-label">
            <input type="checkbox" bind:checked={form.reminder_enabled} />
            <span>Enable daily reminder</span>
          </label>
          {#if form.reminder_enabled}
            <input 
              type="time" 
              bind:value={form.reminder_time}
              class="reminder-time"
            />
          {/if}
        </div>

        <!-- Actions -->
        <div class="modal-actions">
          <button type="button" class="btn-cancel" on:click={close}>Cancel</button>
          <button type="submit" class="btn-submit" disabled={!form.name.trim()}>
            {mode === 'edit' ? 'Save Changes' : 'Create Habit'}
          </button>
        </div>
      </form>
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    padding: 1rem;
  }

  .modal {
    background: var(--bg);
    border-radius: 1rem;
    width: 100%;
    max-width: 500px;
    max-height: 90vh;
    overflow-y: auto;
    box-shadow: var(--shadow-lg);
  }

  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.5rem;
    border-bottom: 1px solid var(--border);
  }

  .modal-header h2 {
    font-size: 1.25rem;
    font-weight: 700;
  }

  .close-btn {
    width: 2rem;
    height: 2rem;
    border-radius: 0.375rem;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--text-secondary);
    font-size: 1.125rem;
  }

  .close-btn:hover {
    background: var(--bg-tertiary);
  }

  .modal-body {
    padding: 1.5rem;
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
  }

  .icon-color-row {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .icon-selector {
    position: relative;
  }

  .icon-display {
    width: 3.5rem;
    height: 3.5rem;
    border-radius: 0.75rem;
    font-size: 1.75rem;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 2px solid var(--border);
    transition: all 0.15s;
  }

  .icon-display:hover {
    border-color: var(--primary);
  }

  .icon-picker {
    position: absolute;
    top: 4rem;
    left: 0;
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 0.5rem;
    padding: 0.5rem;
    display: grid;
    grid-template-columns: repeat(8, 1fr);
    gap: 0.25rem;
    box-shadow: var(--shadow-lg);
    z-index: 10;
    width: 280px;
  }

  .icon-option {
    width: 2rem;
    height: 2rem;
    border-radius: 0.25rem;
    font-size: 1.125rem;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .icon-option:hover {
    background: var(--bg-tertiary);
  }

  .icon-option.selected {
    background: var(--primary);
  }

  .color-selector {
    display: flex;
    gap: 0.5rem;
    flex-wrap: wrap;
  }

  .color-option {
    width: 1.75rem;
    height: 1.75rem;
    border-radius: 50%;
    border: 2px solid transparent;
    transition: all 0.15s;
  }

  .color-option:hover {
    transform: scale(1.15);
  }

  .color-option.selected {
    border-color: var(--text);
    box-shadow: 0 0 0 2px var(--bg), 0 0 0 4px var(--text);
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }

  .form-group label {
    font-size: 0.8125rem;
    font-weight: 600;
    color: var(--text-secondary);
  }

  .form-group input, .form-group textarea, .form-group select {
    padding: 0.625rem 0.75rem;
    border: 1px solid var(--border);
    border-radius: 0.5rem;
    background: var(--bg);
    color: var(--text);
    font-size: 0.875rem;
  }

  .form-group input:focus, .form-group textarea:focus, .form-group select:focus {
    outline: none;
    border-color: var(--primary);
    box-shadow: 0 0 0 2px rgba(16, 185, 129, 0.1);
  }

  .form-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
  }

  .reminder-group {
    flex-direction: row;
    align-items: center;
    gap: 1rem;
  }

  .checkbox-label {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    cursor: pointer;
    font-size: 0.875rem;
    color: var(--text);
  }

  .reminder-time {
    padding: 0.375rem 0.5rem;
    border: 1px solid var(--border);
    border-radius: 0.375rem;
    font-size: 0.875rem;
  }

  .modal-actions {
    display: flex;
    gap: 0.75rem;
    justify-content: flex-end;
    padding-top: 0.5rem;
  }

  .btn-cancel {
    padding: 0.625rem 1.25rem;
    border-radius: 0.5rem;
    color: var(--text-secondary);
    font-weight: 600;
    font-size: 0.875rem;
  }

  .btn-cancel:hover {
    background: var(--bg-tertiary);
  }

  .btn-submit {
    padding: 0.625rem 1.5rem;
    background: var(--primary);
    color: white;
    border-radius: 0.5rem;
    font-weight: 600;
    font-size: 0.875rem;
    transition: all 0.15s;
  }

  .btn-submit:hover:not(:disabled) {
    background: var(--primary-dark);
  }

  .btn-submit:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>
