// src/components/Layout/Sidebar.jsx
import React from 'react';
import { useStore } from '../../lib/store';
import { View, Text, Icon, Badge, Divider } from 'reshaped';
import {
  LayoutDashboard, BookOpen, BarChart3, Settings, HelpCircle,
  Flame, Target, Trophy, Zap, ChevronRight, Sprout
} from 'lucide-react';

const navItems = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { id: 'journal', label: 'Journal', icon: BookOpen },
  { id: 'stats', label: 'Statistics', icon: BarChart3 },
  { id: 'settings', label: 'Settings', icon: Settings },
];

export default function Sidebar() {
  const { currentView, setView, habits, completions, xp, level } = useStore();
  const activeHabits = habits.filter(h => !h.archived);
  const today = new Date().toISOString().split('T')[0];
  const todayDone = completions.filter(c => c.date === today).length;

  return (
    <aside className="app-sidebar">
      <View padding={5} gap={4} height="100%" direction="column">
        {/* Logo */}
        <View direction="row" align="center" gap={2} paddingBottom={3}>
          <div style={{
            width: 36, height: 36, borderRadius: 10,
            background: 'linear-gradient(135deg, #22c55e, #16a34a)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            color: 'white', boxShadow: '0 4px 12px rgba(34,197,94,0.3)'
          }}>
            <Sprout size={18} />
          </div>
          <View>
            <Text variant="title-3" weight="bold">Habitt</Text>
            <Text variant="caption-1" color="neutral-faded">Build better habits</Text>
          </View>
        </View>

        <Divider />

        {/* Navigation */}
        <View gap={1}>
          {navItems.map((item) => {
            const isActive = currentView === item.id;
            return (
              <button
                key={item.id}
                onClick={() => setView(item.id)}
                style={{
                  display: 'flex', alignItems: 'center', gap: '0.75rem',
                  width: '100%', padding: '0.625rem 0.75rem', borderRadius: '12px',
                  background: isActive ? 'var(--rs-color-background-primary-faded)' : 'transparent',
                  border: 'none', cursor: 'pointer', transition: 'all 0.15s',
                  color: isActive ? 'var(--rs-color-foreground-primary-default)' : 'var(--rs-color-foreground-neutral-default)',
                  fontWeight: isActive ? 600 : 500, fontSize: '0.875rem',
                }}
                onMouseEnter={(e) => { if (!isActive) e.currentTarget.style.background = 'var(--rs-color-background-neutral-faded)'; }}
                onMouseLeave={(e) => { if (!isActive) e.currentTarget.style.background = 'transparent'; }}
              >
                <Icon svg={<item.icon size={18} />} />
                <span style={{ flex: 1, textAlign: 'left' }}>{item.label}</span>
                {isActive && <ChevronRight size={14} />}
              </button>
            );
          })}
        </View>

        <Divider />

        {/* Quick Stats */}
        <View gap={2}>
          <Text variant="caption-1" weight="bold" style={{ textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            Today
          </Text>

          <View direction="row" align="center" gap={2} padding={2} style={{
            background: 'var(--rs-color-background-neutral-faded)', borderRadius: '12px'
          }}>
            <Flame size={18} color="#f97316" />
            <Text variant="body-2" style={{ flex: 1 }}>{todayDone} / {activeHabits.length} done</Text>
          </View>

          <View direction="row" align="center" gap={2} padding={2} style={{
            background: 'var(--rs-color-background-neutral-faded)', borderRadius: '12px'
          }}>
            <Target size={18} color="#3b82f6" />
            <Text variant="body-2" style={{ flex: 1 }}>{activeHabits.length} active habits</Text>
          </View>

          {/* XP & Level */}
          <View direction="row" align="center" gap={2} padding={2} style={{
            background: 'linear-gradient(135deg, rgba(139,92,246,0.08), rgba(59,130,246,0.04))',
            borderRadius: '12px', border: '1px solid rgba(139,92,246,0.15)'
          }}>
            <Trophy size={18} color="#8b5cf6" />
            <View style={{ flex: 1 }}>
              <Text variant="caption-1" weight="bold">Level {level}</Text>
              <div style={{
                height: 4, borderRadius: 99, background: 'var(--rs-color-background-neutral-faded)',
                marginTop: 4, overflow: 'hidden'
              }}>
                <div style={{
                  height: '100%', borderRadius: 99,
                  background: 'linear-gradient(90deg, #8b5cf6, #3b82f6)',
                  width: `${(xp % 100)}%`, transition: 'width 0.5s ease'
                }} />
              </div>
            </View>
            <Badge rounded color="primary" variant="faded" size="small">{xp} XP</Badge>
          </View>
        </View>

        {/* Bottom */}
        <div style={{ marginTop: 'auto' }}>
          <Divider />
          <View paddingTop={2}>
            <button
              onClick={() => setView('tutorial')}
              style={{
                display: 'flex', alignItems: 'center', gap: '0.75rem',
                width: '100%', padding: '0.5rem 0.75rem', borderRadius: '12px',
                background: 'transparent', border: 'none', cursor: 'pointer',
                color: 'var(--rs-color-foreground-neutral-faded)', fontSize: '0.8125rem',
              }}
              onMouseEnter={(e) => e.currentTarget.style.background = 'var(--rs-color-background-neutral-faded)'}
              onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
            >
              <HelpCircle size={16} />
              <span>Help and Tutorial</span>
            </button>
            <View direction="row" align="center" gap={1} padding={2} style={{ justifyContent: 'center' }}>
              <Zap size={12} color="var(--rs-color-foreground-neutral-faded)" />
              <Text variant="caption-2" color="neutral-faded">Ctrl+K for commands</Text>
            </View>
          </View>
        </div>
      </View>
    </aside>
  );
}

// src/lib/components/Sidebar.svelte
<script>
  import { currentView, habits, todayCompletions, currentStreaks } from '../stores.js';

  const navItems = [
    { id: 'dashboard', label: 'Dashboard', icon: '📊' },
    { id: 'journal', label: 'Journal', icon: '📝' },
    { id: 'settings', label: 'Settings', icon: '⚙️' },
  ];

  function navigate(view) {
    currentView.set(view);
  }
</script>

<nav class="sidebar">
  <div class="sidebar-header">
    <h1 class="logo">Habitt.</h1>
    <p class="logo-subtitle">Build better habits</p>
  </div>

  <div class="nav-section">
    {#each navItems as item}
      <button
        class="nav-item"
        class:active={$currentView === item.id}
        on:click={() => navigate(item.id)}
      >
        <span class="nav-icon">{item.icon}</span>
        <span class="nav-label">{item.label}</span>
      </button>
    {/each}
  </div>

  <div class="nav-section">
    <div class="section-label">Quick Stats</div>
    <div class="stat-item">
      <span class="stat-icon">🔥</span>
      <span class="stat-label">Today</span>
      <span class="stat-value">{$todayCompletions.length}/{$habits.filter(h => !h.archived).length}</span>
    </div>
    <div class="stat-item">
      <span class="stat-icon">📈</span>
      <span class="stat-label">Habits</span>
      <span class="stat-value">{$habits.filter(h => !h.archived).length}</span>
    </div>
  </div>

  <div class="sidebar-footer">
    <button class="nav-item" on:click={() => navigate('tutorial')}>
      <span class="nav-icon">❓</span>
      <span class="nav-label">Help & Tutorial</span>
    </button>
  </div>
</nav>

<style>
  .sidebar {
    width: 240px;
    background: var(--bg-secondary);
    border-right: 1px solid var(--border);
    display: flex;
    flex-direction: column;
    padding: 1.5rem 0;
    overflow-y: auto;
  }

  .sidebar-header {
    padding: 0 1.5rem 1.5rem;
    border-bottom: 1px solid var(--border);
  }

  .logo {
    font-size: 1.75rem;
    font-weight: 800;
    color: var(--primary);
    letter-spacing: -0.5px;
  }

  .logo-subtitle {
    font-size: 0.75rem;
    color: var(--text-secondary);
    margin-top: 0.25rem;
  }

  .nav-section {
    padding: 1rem 0.75rem;
  }

  .section-label {
    font-size: 0.7rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--text-secondary);
    padding: 0 0.75rem 0.5rem;
  }

  .nav-item {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    width: 100%;
    padding: 0.625rem 0.75rem;
    border-radius: 0.5rem;
    color: var(--text);
    font-size: 0.875rem;
    font-weight: 500;
    transition: all 0.15s;
  }

  .nav-item:hover {
    background: var(--bg-tertiary);
  }

  .nav-item.active {
    background: var(--primary);
    color: white;
  }

  .nav-icon {
    font-size: 1.125rem;
    width: 1.5rem;
    text-align: center;
  }

  .stat-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.5rem 0.75rem;
    font-size: 0.8125rem;
  }

  .stat-icon {
    font-size: 1rem;
  }

  .stat-label {
    flex: 1;
    color: var(--text-secondary);
  }

  .stat-value {
    font-weight: 600;
    color: var(--text);
  }

  .sidebar-footer {
    margin-top: auto;
    padding: 1rem 0.75rem;
    border-top: 1px solid var(--border);
  }
</style>
